IT-NOVATION/BackEnd

ItNovation/.gitignore
ItNovation/src/main/java/com/ItsTime/ItNovation/controller/movie/MovieController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/movie/MovieService.java
ItNovation/src/main/resources/application.yml

movie 패키지에 관련하여 기능들 추가했습니다. 간단하게 요약하면 영화 크롤링 관련 기능들입니다.

영화 크롤링해서 보여주기

---

ItNovation/src/main/java/com/ItsTime/ItNovation/controller/movie/MovieController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/entity/movie/Movie.java
ItNovation/src/main/java/com/ItsTime/ItNovation/entity/movie/MovieRepository.java
ItNovation/src/main/java/com/ItsTime/ItNovation/entity/movie/dto/MovieSaveRequestDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/movie/MovieCrawlService.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/movie/MovieRepoService.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/movie/MovieService.java
ItNovation/src/main/resources/application.yml
ItNovation/src/main/resources/templates/movie.html
ItNovation/src/test/java/com/ItsTime/ItNovation/service/movie/MovieRepoServiceTest.java

영화 이름, posterURL DB에 저장 기능 추가(id통해 찾는 테스트 추가)

---

ItNovation/src/main/java/com/ItsTime/ItNovation/controller/user/UserController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/controller/user/UserSearchController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/review/dto/SearchUserReviewDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/user/User.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/user/UserRepository.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/user/dto/UserSearchRequestDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/user/dto/UserSearchResponseDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/user/UserSearchService.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/user/UserService.java

중간에 jpql을 사용하는 구문을 넣었습니다! 이 부분 궁금하시면 바로 review 달아주세요! UserRepository에 있습니다!
성공했을때 다음과 같이 응답이 돌아옵니다. 자세한 response 정보들은 api 명세서를 확인해주세요!

Feature/searchUser (기능 구현)

---

ItNovation/src/main/java/com/ItsTime/ItNovation/config/SecurityConfig.java
ItNovation/src/main/java/com/ItsTime/ItNovation/controller/review/ReviewController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/controller/user/UserController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/controller/user/UserSearchController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/movie/dto/ReviewMovieInfoDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/review/dto/ReviewInfoDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/review/dto/ReviewReadRequestDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/review/dto/ReviewReadResponseDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/review/dto/SearchUserReviewDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/user/User.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/user/UserRepository.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/user/dto/ReviewUserInfoDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/user/dto/UserSearchRequestDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/user/dto/UserSearchResponseDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/review/ReviewService.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/user/UserSearchService.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/user/UserService.java

리뷰 읽기 관련 기능 구현하였습니다. 
기능을 구현하다가 response 를 확인해보는 도중에  null값들에 대해서 발견하게 되었습니다. 이런 값들에 대한 처리는 다른 api 구현 진행과 함께 보면서 진행해야 될 거 같습니다!

Feature/reviewInfo (리뷰 읽기 관련 기능 구현)

---

ItNovation/src/main/java/com/ItsTime/ItNovation/config/SecurityConfig.java
ItNovation/src/main/java/com/ItsTime/ItNovation/controller/topuser/TopUserController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/bestUser/TopUserResponseDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/follow/FollowRepository.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/movie/dto/TopUserMovieDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/review/ReviewRepository.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/review/dto/TopUserReviewDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/reviewLike/ReviewLikeRepository.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/best/TodayBestReviewService.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/best/TodayBestUserService.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/movie/MovieCrawlService.java

/today/topUser 를 붙이면 바로 진행이 됩니다! 회원가입 없이 바로 진행이 가능하게 구현하였습니다.
(comment 관련 확실하지 않아서 추가 X)
아직 정확한 오류 발생 상황을 체크하지 못하여서 계속 수정해나가도록 하겠습니다!
문제 생기시면 바로 말씀해주세요!

Feature/top user topUser 표시를 위한 api 구현

---

ItNovation/src/main/java/com/ItsTime/ItNovation/controller/user/UserController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/user/dto/LoginStateDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/jwt/filter/JwtAuthenticationProcessingFilter.java
ItNovation/src/main/java/com/ItsTime/ItNovation/jwt/service/JwtService.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/user/UserLoginStateService.java

기존 메인 브랜치에서 해당 서비스를 추가했습니다
다른 작업하실때 해당 브랜치 풀해서 작업하시면 좋을거 같아요!

메인 브랜치에서 현재 사용자의 로그인 여부 서비스를 추가했습니다 😿

---

ItNovation/src/main/java/com/ItsTime/ItNovation/config/SecurityConfig.java
ItNovation/src/main/java/com/ItsTime/ItNovation/controller/movie/MovieController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/controller/movie/MovieSearchController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/controller/push/PushController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/controller/review/ReviewController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/controller/single/SingleController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/follow/FollowRepository.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/movie/MovieRepository.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/movieLike/dto/MovieLikeRequestDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/review/dto/ReviewInfoDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/review/dto/ReviewReadRequestDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/star/dto/SingleStarEvaluateDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/star/dto/SingleStarEvaluateRequestDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/user/dto/UserSearchRequestDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/star/StarService.java

1. 로그인 후 접근하는 곳에서 userId를 request로 받지 않도록 코드 수정하였습니다!
2. 몇몇 의미없는 url들 수정되었습니다. /test 가 붙은 곳들..
생각보다 1번 작업으로 인하여 고쳐진 부분들이 많습니다! 나중에 conflict 날 수 있기 때문에 참고 부탁드립니다!

피드백 받은 부분들 고쳐서 올립니다.

---

ItNovation/src/main/java/com/ItsTime/ItNovation/config/SecurityConfig.java
ItNovation/src/main/resources/application.yml

API 테스트 -> 로그아웃기능 토큰 검사에서 제거

---

ItNovation/src/main/java/com/ItsTime/ItNovation/config/SecurityConfig.java
ItNovation/src/main/java/com/ItsTime/ItNovation/controller/MovieLogController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/movielog/dto/MovieLogReviewInfoDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/user/Grade.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/movielog/MovieLogService.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/review/ReviewService.java

리뷰작성 응답 바디 수정 

---

ItNovation/src/main/java/com/ItsTime/ItNovation/jwt/service/JwtService.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/movie/MovieSearchService.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/user/UserLoginStateService.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/user/UserSearchService.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/user/UserService.java

loginState 에서 로그아웃 후 토큰 만료 여부 확인해주세요!

로그아웃된 토큰 전역으로 관리하게 수정하였습니다

---

ItNovation/src/main/java/com/ItsTime/ItNovation/controller/review/ReviewController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/controller/topfollower/TopFollowerController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/follow/FollowRepository.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/movie/dto/FollowMovieResponseDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/review/dto/TopFollowerReviewResponseDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/topFollower/TopFollowerResponseDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/topFollower/TopFollowerService.java

1. 팔로워 수가 가장 많은 유저의 정보를 담고 있습니다.
2. 해당 유저의 리뷰를 담고 있습니다.
3. 해당 리뷰의 영화 정보를 담고 있습니다.
추후 일부 수정할 계획입니다.

무비토크 인기유저 최종입니다

---

ItNovation/src/main/java/com/ItsTime/ItNovation/controller/latestreview/LatestReviewController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/review/ReviewRepository.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/review/dto/LatestReviewResponseDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/review/ReviewService.java

1. 쿼리문 수정을 통해 가장 최근에 리뷰를 작성한 User 3명을 담아오는 것으로 수정했습니다.
2. Pageable 수정을 통해 각 User가 최근에 작성한 Review를 2개씩 담아오는 것으로 수정했습니다.
3. User 정보에 isMyProfile(내 프로필 여부), loginUserPuhedFollow(팔로우 여부) 추가 했습니다.

무비토크 최신리뷰 최종입니다

---

ItNovation/src/main/java/com/ItsTime/ItNovation/config/SecurityConfig.java
ItNovation/src/main/java/com/ItsTime/ItNovation/controller/movieSearch/MovieAllSearchController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/controller/search/MovieSearchController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/controller/search/UserSearchController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/movie/Movie.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/movie/MovieRepository.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/movieSearch/dto/MovieSearchDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/movieSearch/dto/MovieSearchResponseDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/movieSearch/MovieAllSearchService.java

16개 가져와서 pathvariable 로 가져오고 싶은 page 주면됩니다!
/movie-search/review-order/{page}
/movie-search/star-score-order/{page}
/movie-search/release-order/{page}

리뷰많은순, 평점높은 순, 최근 개봉일 기준 영화 가져오는 무비서치 입니다

---

ItNovation/src/main/java/com/ItsTime/ItNovation/config/SecurityConfig.java
ItNovation/src/main/java/com/ItsTime/ItNovation/controller/review/ReviewController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/review/ReviewRepository.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/review/dto/ReviewInfoDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/reviewLike/ReviewLikeRepository.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/user/dto/UserPushLikeDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/review/ReviewService.java

유저가 해당 영화의 리뷰를 1개만 작성할 수 있도록 1개 작성한 상태에서 요청을 보냈을때 에러코드를 던질 수 있도록 하였습니다!

[fix] 해당 영화의 리뷰를 이미 작성할 경우 오류 반환하는 로직 추가

---

ItNovation/src/main/java/com/ItsTime/ItNovation/config/SecurityConfig.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/comment/CommentRepository.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/review/ReviewRepository.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/user/GradeStandardTable.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/user/User.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/comment/CommentService.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/grade/GradeService.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/review/ReviewService.java

등급 변화 기준에 따라서 등급이 변화합니다!
stardard : 처음 등급
premium : 리뷰 5개, 댓글 10개
vip: 리뷰 10개, 댓글 20개
special: 리뷰 30개, 댓글 30개

Feature/grade change 등급 변경 기준에 따른 등급 변화 기능 추가했습니다.

---

ItNovation/src/main/java/com/ItsTime/ItNovation/controller/search/MovieSearchController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/movie/dto/MovieSearchResponseDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/movie/MovieSearchService.java

1. 검색된 영화가 총 몇 개인지 함께 담아서 보내도록 수정하였습니다.
2. List형식에서 ResponseEntity로 Controller와 Service 비즈니스 로직을 일부 수정하였습니다.

영화 검색기능 - totalSize추가했습니다.

---

ItNovation/src/main/java/com/ItsTime/ItNovation/controller/search/UserSearchController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/user/dto/UserSearchTotalResponseDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/user/UserSearchService.java

1. 검색된 유저가 총 몇 명인지 함께 담아서 보내도록 수정하였습니다.
2. List형식에서 ResponseEntity로 Controller와 Service 비즈니스 로직을 일부 수정하였습니다.

유저  검색 기능 - totalSize 추가했습니다.

---

ItNovation/src/main/java/com/ItsTime/ItNovation/oauth2/handler/OAuth2LoginSuccessHandler.java

[fix] 리다이렉트 url 변경

---

ItNovation/src/main/java/com/ItsTime/ItNovation/service/best/TodayBestReviewService.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/review/ReviewService.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/topFollower/TopFollowerService.java

optional -> get 메서드 제거
무비토크 관련 에러 수정했습니다
로그인 유무 관계없이 올바른 응답 냅니다
한번 확인해주세요!

[fix] 무비토크 사용자 로그인 안했을 경우 error 수정

---

ItNovation/src/main/java/com/ItsTime/ItNovation/oauth2/handler/OAuth2LoginSuccessHandler.java

http://its-movietime.com/ 
해당 도메인으로 소셜로그인 성공 시 리다이렉트 url 변경하였습니다

[fix] 구매한 도메인으로 소셜로그인 성공시 -> 프론트 리다이렉트 url 변경

---

ItNovation/src/main/java/com/ItsTime/ItNovation/controller/search/UserSearchController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/domain/user/dto/UserSearchResponseDto.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/user/UserSearchService.java

[fix] 유저 검색 dto 수정

---

ItNovation/src/main/java/com/ItsTime/ItNovation/service/bestUser/TodayBestUserService.java

[fix] createDate 예쁘게 반응 던질 수 있도록 수정

---

ItNovation/build.gradle
ItNovation/src/main/java/com/ItsTime/ItNovation/config/SecurityConfig.java
ItNovation/src/main/java/com/ItsTime/ItNovation/config/SwaggerConfig.java
ItNovation/src/main/resources/application.yml

http://{도메인}/swagger-ui/index.html#/  로 접속하시면 됩니당
나중에 같이 싹 정리함 해용 👍

[feat] swagger 연결

---

ItNovation/src/main/java/com/ItsTime/ItNovation/common/filter/CorsFilter.java

[fix] cors 필터 수정

---

ItNovation/src/main/java/com/ItsTime/ItNovation/controller/top/TopController.java

앞으로 코드를 작성할때는 try catch 문 범위를 잘 확인합시다. ㅠㅠ

[fix] status 관련 오류 로직 try catch 문 수정

---

ItNovation/src/main/java/com/ItsTime/ItNovation/service/user/UserLoginStateService.java

@djc06048  꼭 확인하세요!
처리가 되지 못한 Exception이 발생하여서 500 오류로 다 대체되어서 internalError 가 발생!
- 코드 내의 catch 부분에서 Exception으로 처리하지 못한 부분에 대한 오류들을 잡아서 처리하도록 진행!
- 우선적으로 그 작업 추후 계속 진행하여 Exception 경우 찾아서 나중에 합친 후 핸들링 하여 특정 Exception으로  catch 하여 처리할 수 있는 방안으로 진행!

[fix] userState 관련 응답 오류 코드 수정 : 처리하지 못한 예외 발생으로 일단 Exception으로 처리 진행

---

ItNovation/.gitignore

- hotfix 처리로 진행되었기 때문에 바로 merge 하도록 하겠습니다.

[chore] gitignore 처리 .DS_Store 관련

---

ItNovation/src/main/java/com/ItsTime/ItNovation/oauth/handler/OAuth2LoginSuccessHandler.java

[chore] 소셜로그인 성공시 리다이렉트 URL 변경

---

ItNovation/src/main/java/com/ItsTime/ItNovation/controller/movie/MovieController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/controller/movie/MovieCrawlController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/controller/movie/SingleMovieController.java
ItNovation/src/main/java/com/ItsTime/ItNovation/service/movie/MovieCrawlService.java

- 메서드 분리 과정 진행
- HashMap -> ConcurrentHashMap으로 변경 (동시성 관련 처리)

[REFACTOR] movie domain 한정 코드 리팩토링 진행하였습니다.

---

ItNovation/src/main/java/com/ItsTime/ItNovation/config/jwt/controller/ReIssueTokenController.java

[FEATURE] 토큰 만료시 토큰 재발급 받는 컨트롤러 추가
